title: Junsik Kim
url: 'https://mibastro.github.io/'
#baseurl: '/example' #change it according to your repository name
permalink: none

#Profile information
name: Junsik Kim
tagline: Postdoctoral Researcher<br>School of Electrical Engineering<br>KAIST
#pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mibastro@gmail.com
website: mibastro.github.io/ #do not add http://
# linkedin: mibastro
github: mibastro
google_scholar: scholar.google.com/citations?user=p5tuyxwAAAAJ&hl=en
cv: cv/CV_JSKim.pdf
# research_statement: assets/files/*.pdf

# Tracker
# analytics: UA-35688210-1
#Update all the sections by editing the files inside _includes folder.

# Build settings
markdown: kramdown